name: Container image mirror to Dockerhub

on:
  workflow_dispatch:
  repository_dispatch:

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TPLATFORMS: linux/amd64,linux/arm64,linux/arm,linux/386

jobs:
  sync-dockerhub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME }}
       
      # https://github.com/regclient/actions
      - name: Install regctl
        uses: regclient/actions/regctl-installer@main

      # WIP
      # https://github.com/regclient/regclient/blob/main/.github/workflows/docker.yml
      - name: Sync GHCR to DockerHub
        run: regsync once --config ../regclient.yml

